name: Deploy Azure Function (Python)

on:
  push:
    branches:
      - main  # or "master" or whatever your default branch is

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'smsredirector'
        package: '.'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
