name: Build and deploy Python function app to Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: 'smsredirector' # ✅ Your Function App name
        package: '.'              # ✅ Root of your repo (where host.json lives)
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
